version: '3.6'

services:
  db:
    image: postgres:14.5
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}
    networks:
      example-network:
        ipv4_address: 172.16.238.11
    
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - ${PG_PORT}
    networks:
      example-network:
        ipv4_address: 172.16.238.12


networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  db:
    driver: local
  pgadmin-data: