import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="min-h-full bg-#F8F8F8">
      <body className="min-h-full">
        <main>{children}</main>
        <footer style={{ marginLeft: '45%', color: '#969696', fontSize: '12px', marginTop: '24px'}}>Designed by @hdpnoph</footer>
      </body>
    </html>
  )
}
