load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")

rust_binary(
    name = "alice_database",
    srcs = ["src/main.rs"],
)

rust_test(
    name = "alice_database_test",
    srcs = ["src/main.rs"],
)