[package]
name = "Kingdom-System-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
amiquip = "0.4.2"
redis = "0.23.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
